openapi: 3.0.0
servers:
  - url: http://localhost:8000/api/
paths:
  /user:
    get:
      security:
        - sanctum: []
      summary: Returns the authenticated user details
      responses:
        200:
          description: User details

  /users:
    get:
      security:
        - sanctum: []
      summary: Returns a list of all users
      responses:
        200:
          description: List of all users

    post:
      security:
        - sanctum: []
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: User created
        409:
          description: Conflict (email or username already used)

  /users/id/{id}:
    get:
      security:
        - sanctum: []
      summary: Returns a user with a specific ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User with the specified ID
    delete:
      security:
        - sanctum: []
      summary: Deletes a user with a specific ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User deleted
    patch:
      security:
        - sanctum: []
      summary: Updates the password of a user with a specific ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        200:
          description: Password updated

  /users/name/{name}:
    get:
      security:
        - sanctum: []
      summary: Returns a user with a specific name
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        200:
          description: User with the specified name

  /tokens/create:
    post:
      summary: Creates a token for an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                token_name:
                  type: string
      responses:
        200:
          description: Token created
